# Generated by Django 3.2 on 2021-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210514_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='snumber',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='学工号'),
        ),
    ]
