# Generated by Django 3.2 on 2021-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210515_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(default='images/userDefault.png', upload_to='', verbose_name='头像'),
        ),
    ]
