# Generated by Django 3.2 on 2021-06-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.CharField(max_length=4, null=True, verbose_name='分数'),
        ),
    ]
