# Generated by Django 3.2 on 2021-05-15 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20210515_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='column',
            field=models.CharField(max_length=200, verbose_name='栏目'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='slug',
            field=models.SlugField(max_length=500, verbose_name='转换'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='articles_like', to=settings.AUTH_USER_MODEL, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='tag',
            field=models.CharField(max_length=500, verbose_name='标签'),
        ),
    ]
