# Generated by Django 3.2 on 2021-05-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210515_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name': '文章栏目', 'verbose_name_plural': '文章栏目'},
        ),
    ]
