# Generated by Django 3.2 on 2021-05-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-publish',), 'verbose_name': '通知信息', 'verbose_name_plural': '通知信息'},
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(default='', verbose_name='通知详情'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=300, verbose_name='通知名'),
        ),
    ]
