# Generated by Django 3.2 on 2021-06-06 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210515_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间'),
        ),
    ]
